name: 'Package installation testing'
description: 'Test that given package can be installed from a given repo'
inputs:
  repo_base_url:
    description: 'base url to the rpm/yum/apt repository of NR'
  package_name:
    description: 'name of a package'
  expected_package_version:
    description: 'version of a package that should be installed'
  gpg_key:
    description: 'gpg key to verify package signatures'
  docker_hub_id:
    description: 'required to avoid rate limiting'
  docker_hub_password:
    description: 'required to avoid rate limiting'
  platforms:
    description: 'comma separated list of platforms with version we want to run test for'

runs:
  using: "composite"
  steps:
    - name: Configure Molecule and Ansible
      shell: bash
      run: |
        sudo pipx uninstall ansible-core
        sudo pip3 install molecule[docker]==3.6.0
        sudo pip3 install 'rich>=10.0.0,<11.0.0'
        sudo pip3 install ansible-lint[community]==5.3.2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_hub_id }}
        password: ${{ inputs.docker_hub_password }}
    - name: Prepare OS versions
      shell: bash
      run: ${GITHUB_ACTION_PATH}/prepare_platform.sh ${{ inputs.platforms }}
    - name: Run molecule
      shell: bash
      env:
        REPO_BASE_URL: ${{ inputs.repo_base_url }}
        PACKAGE_NAME: ${{ inputs.package_name }}
        EXPECTED_PACKAGE_VERSION: ${{ inputs.expected_package_version }}
        GPG_KEY: ${{ inputs.gpg_key }}
      run: "cd ${GITHUB_ACTION_PATH} && molecule converge"
    - name: Teardown
      shell: bash
      run: "cd ${GITHUB_ACTION_PATH} && molecule destroy"
