---

- name: Setup YUM repository
  yum_repository:
    name: "{{ package_name }}"
    description: Molecule packaging tests
    # $releasever var cannot be used as RHEL7 will replace it with 7Server instead of 7.
    baseurl: "{{ repo_endpoint }}/linux/yum/el/{{ ansible_distribution_major_version }}/$basearch"
    gpgkey: http://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    gpgcheck: no
    repo_gpgcheck: no

- name: clean yum cache
  # https://github.com/ansible/ansible/pull/31450#issuecomment-352889579
  command:
    cmd: yum clean all
...
