---

- name: Setup YUM repository
  yum_repository:
    name: "{{ package_name }}"
    description: Molecule packaging tests
    baseurl: "{{ repo_endpoint }}/linux/yum/el/$releasever/$basearch"
    gpgkey: http://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    gpgcheck: no
    repo_gpgcheck: no

- name: clean yum cache
  # https://github.com/ansible/ansible/pull/31450#issuecomment-352889579
  command:
    cmd: yum clean all

...
