---

# name of a file reflecting container OS version
- name: Setup Zypper repository
  zypper_repository:
    name: "{{ package_name }}"
    description: Molecule packaging tests
    repo: "{{ repo_endpoint }}/linux/zypp/sles/{{ansible_distribution_version}}/{{ansible_machine}}/"
    runrefresh: yes
    auto_import_keys: yes
    disable_gpg_check: yes
    state: present

...
