---

- name: Setup newrelic infra APT key
  apt_key:
    url: "{{ gpg_key }}"

- name: Setup APT repository
  apt_repository:
    repo: "deb {{ repo_endpoint }}/linux/apt {{ ansible_distribution_release }} main"
    filename: newrelic-infra
    update_cache: no

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  ignore_errors: true
...
