---

- name: Assert version
  shell: "newrelic-infra --version | grep {{ package_version }} || (>&2 newrelic-infra --version && exit 1)"
  register: check

- name: Stdout from version grep
  debug:
    msg: "{{ check.stdout }}"

...
