---

- name: Zypper package installation
  zypper:
    name: "{{ package_name }}={{ target_agent_version }}"
    state: present
    oldpackage: yes
    update_cache: yes
    force: yes
    disable_gpg_check: true
...
