---

- name: zypper install infra-agent
  environment: "{{ env_vars }}"
  zypper:
    name: "{{ package_name }}={{ target_agent_version }}"
    state: present
    oldpackage: yes
    update_cache: yes
    force: yes
    disable_gpg_check: true
  retries: 5
  delay: 60

...
