---

- name: Apt package installation
  apt:
    name: "{{ package_name }}={{ target_agent_version }}"
    update_cache: no #ubuntu 20.10 image has broken repos. Cache will only be updated after NR repo is added
  retries: 5
  delay: 60
...
